
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jbtok
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn8 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jbtn4 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtncal = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnMeal = new javax.swing.JButton();
        jbtnBurger = new javax.swing.JButton();
        jbtnNuggets = new javax.swing.JButton();
        jbtnFried = new javax.swing.JButton();
        jbtnDonuts = new javax.swing.JButton();
        jbtnSponge = new javax.swing.JButton();
        jbtnSmoothie = new javax.swing.JButton();
        jbtnIceCream = new javax.swing.JButton();
        jbtnCoffee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jbtn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jbtn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 410, 360));

        jbtn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jbtn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jbtn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jbtn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jbtn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jbtn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jbtn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jbtncal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtncal.setText("c");
        jbtncal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jbtnDot.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 290));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnMeal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnMeal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/meal1.jpg"))); // NOI18N
        jbtnMeal.setText("$7");
        jbtnMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMealActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 90));

        jbtnBurger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/R1.png"))); // NOI18N
        jbtnBurger.setText("$4");
        jbtnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBurgerActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 170, 90));

        jbtnNuggets.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnNuggets.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nuggets1.JPG"))); // NOI18N
        jbtnNuggets.setText("$3");
        jbtnNuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuggetsActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnNuggets, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 180, 90));

        jbtnFried.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnFried.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Fried1.gif"))); // NOI18N
        jbtnFried.setText("$1");
        jbtnFried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFriedActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnFried, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 160, 90));

        jbtnDonuts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnDonuts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/donuts1.jpg"))); // NOI18N
        jbtnDonuts.setText("$2");
        jbtnDonuts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDonutsActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDonuts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, 90));

        jbtnSponge.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnSponge.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sponge1.jpg"))); // NOI18N
        jbtnSponge.setText("$1");
        jbtnSponge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSpongeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSponge, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 180, 90));

        jbtnSmoothie.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnSmoothie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/smoothie1.jpg"))); // NOI18N
        jbtnSmoothie.setText("$2");
        jbtnSmoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSmoothieActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSmoothie, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 170, 90));

        jbtnIceCream.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnIceCream.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iceKream1.png"))); // NOI18N
        jbtnIceCream.setText("$3");
        jbtnIceCream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIceCreamActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnIceCream, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 160, 90));

        jbtnCoffee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbtnCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/coffee1.jpg"))); // NOI18N
        jbtnCoffee.setText("$1");
        jbtnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoffeeActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 180, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 610, 350));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 270, 290));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tax");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Total");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 40));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, -1));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 160, -1));

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, 160));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, 40));

        jbtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 40));

        jbtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 140, 40));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 30));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel7.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 40));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 340, 160));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 340, 160));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Payment Method");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Change");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel8.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 140, -1));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel8.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 140, -1));

        jcboPayment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel8.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 140, 30));

        jPanel6.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 390, 160));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 1130, 220));

        jtxtBarCode.setFont(new java.awt.Font("MS Outlook", 1, 24)); // NOI18N
        jtxtBarCode.setText("lllllllllll");
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 270, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
       if (jcboPayment.getSelectedItem().equals("Cash"))
       {
       Change();
       }
       else
       {
               jtxtChange.setText("");
               jtxtDisplay.setText("");
               
               }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jbtnMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMealActionPerformed
        double PriceOfItem = 7;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Meal", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnMealActionPerformed
//========================Function==========================
    
    public void ItemCost(){
    double sum = 0;
    
    for (int i = 0; i < jTable1.getRowCount(); i++){
    sum =sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
    }
    jtxtSubTotal.setText(Double.toString(sum));
    double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
    
    double cTax = (cTotal1 * 3.9)/100;
    String iTaxTotal = String.format("$ %.2f", cTax);
    jtxtTax.setText(iTaxTotal);
    
    String iSubTotal = String.format("$ %.2f", cTotal1);
    jtxtSubTotal.setText(iSubTotal);
    
    String iTotal = String.format("$ %.2f", cTotal1 + cTax);
    jtxtTotal.setText(iTotal);
    
     String BarCode = String.format("Total  is %.2f", cTotal1 + cTax);
    jtxtBarCode.setText(BarCode);
    }
    //========================Function Change==========================
    
    public void Change(){
    
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
      for (int i = 0; i < jTable1.getRowCount(); i++){
    sum =sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
    }   
     double   cTax = (sum * 3.9)/100;
     double cChange = (cash - (sum + cTax));
     
     
     String ChangeGiven = String.format("$ %.2f", cChange);
     jtxtChange.setText(ChangeGiven);
        
        
        
    }
    
    
    
    
    
            
       
    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
       
        String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn7.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn7.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn8.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn8.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
     String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn9.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn9.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
       String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn4.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn4.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
          String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn5.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn5.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
       String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn6.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn6.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
          String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn1.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn1.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
         String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn2.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn2.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
         String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn3.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn3.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
         String EnterNumber = jtxtDisplay.getText();
        
        if(EnterNumber == ""){
        jtxtDisplay.setText(jbtn0.getText());
        }
        else{
        EnterNumber = jtxtDisplay.getText() + jbtn0.getText();
        jtxtDisplay.setText(EnterNumber);
        
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
    if(! jtxtDisplay.getText().contains(".")){
        jtxtDisplay.setText(jtxtDisplay.getText()+jbtnDot.getText());
    }//GEN-LAST:event_jbtnDotActionPerformed
    }
    private void jbtncalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncalActionPerformed
       jtxtDisplay.setText("");
       jtxtChange.setText("");
        
        
    }//GEN-LAST:event_jbtncalActionPerformed

    private void jbtnFriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFriedActionPerformed
      double PriceOfItem = 1;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Fried", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnFriedActionPerformed

    private void jbtnDonutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDonutsActionPerformed
        double PriceOfItem = 2;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Donuts", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnDonutsActionPerformed

    private void jbtnSpongeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSpongeActionPerformed
        double PriceOfItem = 1;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Sponge", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnSpongeActionPerformed

    private void jbtnIceCreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIceCreamActionPerformed
 double PriceOfItem = 3;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Ice Cream", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnIceCreamActionPerformed

    private void jbtnSmoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSmoothieActionPerformed
        double PriceOfItem = 2;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Smoothie", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnSmoothieActionPerformed

    private void jbtnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoffeeActionPerformed
         double PriceOfItem = 1;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Coffee", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnCoffeeActionPerformed

    private void jbtnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBurgerActionPerformed
       double PriceOfItem = 4;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Burger", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnBurgerActionPerformed

    private void jbtnNuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuggetsActionPerformed
        double PriceOfItem = 3;
      
      DefaultTableModel model = (DefaultTableModel) 
              jTable1.getModel();
      model.addRow(new Object[]{"Nuggets", "1", PriceOfItem});
      ItemCost();
    }//GEN-LAST:event_jbtnNuggetsActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      model.setRowCount(0);
        
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
    
        
        MessageFormat header = new MessageFormat ("Printing in Progress");
        MessageFormat footer = new MessageFormat ("Page {0, number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL,header, footer);
        }
        catch(java.awt.print.PrinterException e){
        System.err.format("No Printer found", e.getMessage());
        
        }     
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          int RemoveItem = jTable1.getSelectedRow();
          if(RemoveItem >= 0){
          model.removeRow(RemoveItem);
          }
          ItemCost();
          
          if (jcboPayment.getSelectedItem().equals("Cash"))
            {
               Change();
            }
            else
            {
               jtxtChange.setText("");
               jtxtDisplay.setText("");
               
            }                    
    }//GEN-LAST:event_jbtnRemoveActionPerformed
   private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
       frame = new JFrame("Exit");
       if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Point of Sale",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {   
    }//GEN-LAST:event_jbtnExitActionPerformed
   System.exit(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBurger;
    private javax.swing.JButton jbtnCoffee;
    private javax.swing.JButton jbtnDonuts;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFried;
    private javax.swing.JButton jbtnIceCream;
    private javax.swing.JButton jbtnMeal;
    private javax.swing.JButton jbtnNuggets;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSmoothie;
    private javax.swing.JButton jbtnSponge;
    private javax.swing.JButton jbtncal;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
